blank_issues_enabled: false
contact_links:
  - name: ⚠️ Report Pinboard Service/API Issues
    url: https://pinboard.in
    about: If you see "Cannot check this page on Pinboard," or bookmark titles or tags are loading too slowly, this is most certainly a backend issue. Please contact Pinboard support directly. I do not run the servers.